[package]
name = "scrobble-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
lastfm-client = { version = "1.0.0", path = "../lastfm-client" }
scrobble-core = { version = "1.0.0", path = "../scrobble-core" }
scrobble-storage = { version = "1.0.0", path = "../scrobble-storage" }
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true
ytmusic-client = { version = "1.0.0", path = "../ytmusic-client" }

[dev-dependencies]
reqwest.workspace = true
tokio.workspace = true

[lints]
workspace = true
